extends: ../../default.yaml
output_dir: ./outputs/ecotta/idrid/
model: !include ../../model/retfound.yaml
target_dataset: !include ../../data/idrid.yaml
ctta: !include ../../ecotta/idrid.yaml
prototype:
  temperature: 100.0