extends: ../../default.yaml
output_dir: ./outputs/ecotta/messidor2_visionfm/
model: !include ../../model/visionfm.yaml
target_dataset: !include ../../data/messidor2.yaml
ctta: !include ../../ecotta/messidor2_visionfm.yaml
prototype:
  temperature: 50.0