extends: ../../default.yaml
output_dir: ./outputs/ecotta/messidor2/
model: !include ../../model/retfound.yaml
target_dataset: !include ../../data/messidor2.yaml
ctta: !include ../../ecotta/messidor2.yaml
prototype:
  temperature: 100.0