extends: ../../default.yaml
output_dir: ./outputs/palm/idrid/
model: !include ../../model/retfound.yaml
target_dataset: !include ../../data/idrid.yaml
ctta: !include ../../palm/idrid.yaml
prototype:
  temperature: 100.0
