extends: ../../../default.yaml
output_dir: ./outputs/sequential_vida/aptos_idrid/
model: !include ../../../model/retfound.yaml
prototype:
  temperature: 100.0

sequential:
  enabled: true
  source_dataset:
    name: aptos2019
    data_dir: ./data/APTOS2019/
    ctta: !include ../../../vida/aptos.yaml
  target_datasets:
    - name: idrid
      data_dir: ./data/IDRiD/
      ctta: !include ../../../vida/idrid_target_from_aptos.yaml
  reset_weights_before_each_target: false
