extends: ../../default.yaml
output_dir: ./outputs/vida/idrid_visionfm/
model: !include ../../model/visionfm.yaml
target_dataset: !include ../../data/idrid.yaml
ctta: !include ../../vida/idrid_visionfm.yaml
prototype:
  temperature: 100.0
