extends: ../../../default.yaml
output_dir: ./outputs/sequential_cotta/idrid_messidor_aptos_visionfm/
model: !include ../../../model/visionfm.yaml
prototype:
  temperature: 50.0

sequential:
  enabled: true
  source_dataset:
    name: idrid
    data_dir: ./data/IDRiD/
    ctta: !include ../../../cotta/idrid_visionfm.yaml
  target_datasets:
    - name: messidor2
      data_dir: ./data/MESSIDOR2/
      ctta: !include ../../../cotta/messidor2_visionfm_target_from_idrid.yaml
    - name: aptos2019
      data_dir: ./data/APTOS2019/
      ctta: !include ../../../cotta/aptos_visionfm_target_from_idrid.yaml
  reset_weights_before_each_target: false
