extends: ../../default.yaml
output_dir: ./outputs/cotta/aptos_visionfm/
model: !include ../../model/visionfm.yaml
target_dataset: !include ../../data/aptos2019.yaml
ctta: !include ../../cotta/aptos_visionfm.yaml
prototype:
  temperature: 50.0
