extends: ../../default.yaml
output_dir: ./outputs/cotta/idrid_visionfm/
model: !include ../../model/visionfm.yaml
target_dataset: !include ../../data/idrid.yaml
ctta: !include ../../cotta/idrid_visionfm.yaml
prototype:
  temperature: 50.0
